server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  type-aliases-package: cn.itcast.service.pojo